# Generated by Django 2.1.7 on 2019-05-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190508_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='broker',
            new_name='biztype',
        ),
    ]
